apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: web-server
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
  selector:
    matchLabels:
      app: web-server
  replicas: 3
