apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 80 # No caso de ClusterIp somente a definição da porta é o suficiente
      nodePort: 30000 # Exposição da porta 30000 redirecionando para a porta 80 do Pod
      # OBS: The range of valid ports is 30000-32767
  selector:
    app: web-server
